### ISSUE TITLE
[BUG]: potential problems when maker sets min_vol and max_vol to same value

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet-desktop#2183]
This might also be an issue in webdex, and same case should be tested in CLI.
It was noted that previously desktop maker orders would default to this is taker not fulfilled in time - we need to cover what to do in this case.

**Comment by cipig** [comment]
there are couple of orders in orderbook with min_volume = max_volume
starting a swap with those as taker works fine after GUI switched to using fractional/rational numbers for volume instead of decimals (because of the rounding)... i filled a lot of those orders and didn't had any problems
idk though how and why maker set min_volume = max_volume

**Comment by cipig** [comment]
indeed, if you change volume with the % buttons, it will not match any more... same would apply with other orders too (where min_volume != max_volume) if you go lower then min_volume with those buttons
looks like the buttons need a check to not go below min_volume of the order when a specific order from orderbook was selected

**Comment by smk762** [comment]
closing as stale
