### ISSUE TITLE
[BUG]: DEX tab is infinitely loading market data. Also prices for coins that are to be swapped are 0.

### ISSUE THREAD

**Issue by segfaultDelirium** [KomodoPlatform/komodo-wallet-desktop#2344]
**Describe the bug**
As visible on the screenshot the "loading market data..." never stops loading. The Orders and History tabs (next to Chart tab) are empty. 
![komodo_wallet_dex_shows_0_and_history_not_loading](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/82722872/75563133-f8cd-4c90-acea-91eaed54b4f7)

Furthermore the coins to be swapped show price 0
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/82722872/ed4ec2f9-2400-4ea4-8ad5-a94f0ee7f5fb)

**To Reproduce**
1. Go to DEX tab on sidebar
2. Select Pro view (contrary to Simple view)
3. See error

**Expected behavior**
The charts loads and prices for cryptocurrencies are not 0.

**Operating Environment(s):**
 - OS: [e.g. Windows/OSX/Linux. If Linux, include distro. ] Linux Manjaro
 - OS version: [e.g. 7/10/11, 10.13/10.15, 18.04/20.04 ] 6.1.44-1-MANJARO
 - Komodo Wallet Version: [e.g. 0.6.0] 0.6.0-beta (AppImage)
 - Build branch: [e.g. master/dev] 

**Additional context**
 - Add any related context about the problem here (e.g. screen resolution, mining activity on address)
 - Attach [log files](https://forum.komodoplatform.com/t/accessing-atomicdex-desktop-log-files/540)

**Comment by smk762** [comment]
`Loading market data` loop may be due to network conditions. Graph comes from LiveCoinWatch. Its working here, so maybe your location (or VPN) is rejecting it.

Zero balances is normal if you have no funds. Without posting an address I cant verify if this is accurate.
Orders and history will be empty if you have not done any swaps, or have any in progress. Without posting swap UUIDs, I cant verify this as accurate.

No log files provided either, so there is not enough actionable information in this issue to do anything, so it will be closed. Feel free to reopen it if you have more information to add.
