### ISSUE TITLE
[BUG]: Multiple notifications (Both send and receive) for the same transaction

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/komodo-wallet-desktop#591]
**Describe the bug**
When a transaction in which the external address sends all of its coins to the AtomicDEX desktop address, Example txn: https://rick.kmd.dev/tx/7b98331998ae54ad69c215f6e12322c184201fc4a3a09fafb2e437e591bf18b7, the application displays notifications that say both `received` and `sent` for the same amount

**To Reproduce**
1. Send the whole balance from an external RICK address to the AtomicDEX RICK address while the application is running. 
2. Wait a while for the transaction to confirm and observe the notifications.

**Expected behavior**
No sent notification is displayed when the wallet receives coins

**Screenshots**

Notifications: All of them were received because of the same receive txn

![Screenshot from 2020-11-30 13-30-38](https://user-images.githubusercontent.com/21151592/100584162-bb041680-3311-11eb-82fe-2a13f5f41288.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version : Desktop v0.3.0-beta

**Additional context**
Addresses Involved:

- AtomicDEX desktop address: RDcSRqZZRZwbtoMPjsXLXinZ2oPXC5nBdV
- External address: RVNKRr2uxPMxJeDwFnTKjdtiLtcs7UzCZn

**Comment by tonymorony** [comment]
Thanks for the issue opening! 

Thats known problem caused by UTXO specifics and by how notifications implemented atm (tracking balance changing)

I do propose to track tx history instead @Milerius

**Comment by Milerius** [comment]
> Thanks for the issue opening!
> 
> Thats known problem caused by UTXO specifics and by how notifications implemented atm (tracking balance changing)
> 
> I do propose to track tx history instead @Milerius

The problem is that tracking the change of the transaction history is almost mission impossible, we have a very optimized history, which loads partially according to the scroll, the detection of new transactions is not managed by the model itself , if there is a difference in size it is not a problem -> it is filter by the date of transaction

I'm sure it's possible by tracking the balance, but in a different way, i will check that too

**Comment by Milerius** [comment]
I checked again this morning, I confirm the tracking of the transaction history is not possible for the moment because for optimization reasons only the history of the currently selected `coin` is loaded in memory (this allowed us big savings in the past, tracking the balance change seems to me to be appropriate, we just need an option to figure out when it comes from `UTXO` most of the time this just work's correctly.

PS: The behaviour also select the coin of the tracked balance when you click on the notification which loads your tx history

**Comment by cipig** [comment]
This happens quite often:
![image](https://user-images.githubusercontent.com/32116761/115808878-a4527f00-a3da-11eb-86d3-91f4f2410c57.png)
![image](https://user-images.githubusercontent.com/32116761/115808896-ab798d00-a3da-11eb-97c2-8f682f9b8c4e.png)
-----
![image](https://user-images.githubusercontent.com/32116761/115808921-b46a5e80-a3da-11eb-94e3-3b68f42bf604.png)
![image](https://user-images.githubusercontent.com/32116761/115808934-ba603f80-a3da-11eb-99a1-fe294de00f67.png)

changing the frequency of balance checks to >> 60s will likely solve the issue, i propose 130s

**Comment by damascene** [comment]
![image](https://user-images.githubusercontent.com/411046/131466192-9ebab56b-3355-429b-8412-e0993fe52675.png)
Having the same issue. Got three notifications for the same transaction.

**Comment by smk762** [comment]
Issue not encountered recently. Will reopen if new reports recieved.
